"""remove unique constraint from chat room name

Revision ID: 16d7d55f187f
Revises: 1a9f5517266f
Create Date: 2026-07-31 17:14:50.914501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d7d55f187f'
down_revision: Union[str, Sequence[str], None] = '1a9f5517266f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_rooms_name'), table_name='chat_rooms')
    op.create_index(op.f('ix_chat_rooms_name'), 'chat_rooms', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_rooms_name'), table_name='chat_rooms')
    op.create_index(op.f('ix_chat_rooms_name'), 'chat_rooms', ['name'], unique=True)
    # ### end Alembic commands ###
